# Generated by Django 4.1.7 on 2023-11-14 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='eequests',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bywho', models.CharField(max_length=120)),
                ('uuid', models.CharField(max_length=120)),
            ],
        ),
    ]
