# Generated by Django 4.2.5 on 2023-11-06 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phone_number1',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='student',
            name='phone_number2',
            field=models.CharField(max_length=15),
        ),
    ]
