# Generated by Django 4.2.5 on 2023-11-06 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_alter_student_phone_number1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cource',
            name='Teacher',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='student.teacher'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='cource',
            field=models.ManyToManyField(to='student.cource'),
        ),
        migrations.AddField(
            model_name='student',
            name='cource_limet',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(default=0, upload_to='techer_img'),
            preserve_default=False,
        ),
    ]
