# Generated by Django 4.2.5 on 2023-11-06 11:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0002_fiald_video_mcq_answer_alter_fiald_answer_and_more'),
        ('student', '0003_cource_teacher_student_cource_student_cource_limet_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cource',
            old_name='Teacher',
            new_name='Teache',
        ),
        migrations.AddField(
            model_name='student',
            name='Form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='form.form'),
        ),
        migrations.AddField(
            model_name='student',
            name='editbal',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
