# Generated by Django 4.2.5 on 2023-11-07 07:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_rename_teacher_cource_teache_student_form_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cource',
            old_name='Teache',
            new_name='Teacher',
        ),
    ]
