# Generated by Django 4.2.5 on 2023-11-07 08:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_rename_teache_cource_teacher'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='col',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacher',
            name='row',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
