# Generated by Django 4.1.7 on 2023-11-18 11:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('form', '0019_form_next_step'),
        ('student', '0006_teacher_col_teacher_row'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='form',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='form.form'),
        ),
    ]
